#!/usr/bin/env python3
"""
Language configuration for Deep Research reports.

Shared template for all Latin-script languages, per-language overrides
only specify the translated strings. `get_lang_config(lang)` returns
the merged config.
"""

CHINESE_NUMERALS = ['一', '二', '三', '四', '五', '六', '七', '八', '九', '十',
                    '十一', '十二', '十三', '十四', '十五']

# ── Shared structural elements (not language-specific) ──

_LATIN_CHAPTER = lambda n, title: f"## {n}. {title}"
_LATIN_PREFIX = lambda n: f"{n}."
_LATIN_TOC = lambda prefix, title, anchor: f"- [{prefix} {title}](#{anchor})"

_ZH_CHAPTER = lambda n, title: f"## {CHINESE_NUMERALS[n-1]}、{title}"
_ZH_PREFIX = lambda n: CHINESE_NUMERALS[n-1] + "、"
_ZH_TOC = lambda prefix, title, anchor: f"- [{prefix}{title}](#{anchor})"

# Base template for all 18 non-zh languages
_BASE_LATIN = {
    "sep": " · ",
    "field_sep": ": ",
    "minute_unit": "min",
    "chapter_heading": _LATIN_CHAPTER,
    "toc_prefix": _LATIN_PREFIX,
    "toc_line": _LATIN_TOC,
    "promo_line": "*Generated by [deep-research](https://github.com/hoolulu/deep-research) · One command. Ten minutes. Deep professional reports.*",
    "check": {
        "ch_number_pattern": r'^## \d+\.',
        "ch_has_number_check": True,
    }
}

_BASE_ZH = {
    "sep": " · ",
    "field_sep": "：",
    "minute_unit": "分钟",
    "chapter_heading": _ZH_CHAPTER,
    "toc_prefix": _ZH_PREFIX,
    "toc_line": _ZH_TOC,
    "promo_line": "*本报告由 [deep-research](https://github.com/hoolulu/deep-research) 自动生成 · 一个命令，十分钟，一份深度专业报告*",
    "check": {
        "ch_number_pattern": r'^## ([' + ''.join(CHINESE_NUMERALS) + r']+)、',
        "ch_has_number_check": False,
    }
}

# ── Per-language translated strings only ──
# Each entry specifies only what's different from the base template.
# The fields are: metadata_fields, metadata_label, references_label,
# refs_prefix, refs_count_format, toc_heading, disclaimer_title,
# disclaimer_text, confidence_heading, verdict_labels, report_generated,
# check:{metadata_pattern, references_pattern, tail_refs, tail_disclaimer, tail_confidence}

_LANG = {

"zh": {
    "metadata_fields": ["总字数", "阅读时间", "数据截至", "生成时间", "调研模式", "Skill版本"],
    "metadata_label": "**元数据**：",
    "references_label": "**参考来源**：",
    "refs_prefix": "## 参考来源",
    "refs_count_format": "共引用 {count} 个来源",
    "toc_heading": "## 目录",
    "disclaimer_title": "## 免责声明",
    "disclaimer_text": "本报告基于公开数据整理，不构成投资建议。部分存疑数据已标明，请自行谨慎判断。",
    "confidence_heading": "## 可信评估",
    "verdict_labels": {"reliable": "结论可靠", "moderate": "基本可信", "caution": "谨慎参考"},
    "report_generated": "*报告生成时间：{time}*",
    "check": {
        "metadata_pattern": r'> \*\*元数据\*\*：',
        "references_pattern": r'> \*\*参考来源\*\*',
        "tail_refs": "## 参考来源",
        "tail_disclaimer": "## 免责声明",
        "tail_confidence": "## 可信评估",
    }
},

"en": {
    "metadata_fields": ["Word Count", "Reading Time", "Data Until", "Generated", "Mode", "Skill Version"],
    "metadata_label": "**Metadata**:",
    "references_label": "**References**:",
    "refs_prefix": "## References",
    "refs_count_format": "Total {count} sources",
    "toc_heading": "## Table of Contents",
    "disclaimer_title": "## Disclaimer",
    "disclaimer_text": "This report is compiled from publicly available data and does not constitute investment advice. Some data points are marked as questionable — please exercise your own judgment.",
    "confidence_heading": "## Confidence Assessment",
    "verdict_labels": {"reliable": "Reliable", "moderate": "Moderate", "caution": "Caution"},
    "report_generated": "*Report generated: {time}*",
    "check": {
        "metadata_pattern": r'> \*\*Metadata\*\*:',
        "references_pattern": r'> \*\*References\*\*',
        "tail_refs": "## References",
        "tail_disclaimer": "## Disclaimer",
        "tail_confidence": "## Confidence Assessment",
    }
},

"ja": {
    "metadata_fields": ["文字数", "読了時間", "データ期限", "生成時間", "モード", "Skillバージョン"],
    "metadata_label": "**メタデータ**:",
    "references_label": "**参照元**:",
    "refs_prefix": "## 参照元",
    "refs_count_format": "合計 {count} 件の出典",
    "toc_heading": "## 目次",
    "disclaimer_title": "## 免責事項",
    "disclaimer_text": "本レポートは公開データに基づき作成されたものであり、投資助言を構成するものではありません。疑わしいデータには注釈を付しています。",
    "confidence_heading": "## 信頼性評価",
    "verdict_labels": {"reliable": "信頼できる", "moderate": "ほぼ信頼", "caution": "注意"},
    "report_generated": "*生成時間：{time}*",
    "check": {
        "metadata_pattern": r'> \*\*メタデータ\*\*:',
        "references_pattern": r'> \*\*参照元\*\*',
        "tail_refs": "## 参照元",
        "tail_disclaimer": "## 免責事項",
        "tail_confidence": "## 信頼性評価",
    }
},

"ko": {
    "metadata_fields": ["글자 수", "읽는 시간", "데이터 기준일", "생성 시간", "모드", "Skill 버전"],
    "metadata_label": "**메타데이터**:",
    "references_label": "**참고 자료**:",
    "refs_prefix": "## 참고 자료",
    "refs_count_format": "총 {count}개 출처",
    "toc_heading": "## 목차",
    "disclaimer_title": "## 면책 조항",
    "disclaimer_text": "본 보고서는 공개 데이터를 기반으로 작성되었으며 투자 조언을 구성하지 않습니다. 의심스러운 데이터는 별도 표기되었습니다.",
    "confidence_heading": "## 신뢰도 평가",
    "verdict_labels": {"reliable": "신뢰 가능", "moderate": "대체로 신뢰", "caution": "주의"},
    "report_generated": "*생성 시간：{time}*",
    "check": {
        "metadata_pattern": r'> \*\*메타데이터\*\*:',
        "references_pattern": r'> \*\*참고 자료\*\*',
        "tail_refs": "## 참고 자료",
        "tail_disclaimer": "## 면책 조항",
        "tail_confidence": "## 신뢰도 평가",
    }
},

# ── Latin-script languages (en/es/fr/de/pt/it/nl/sv) ──
# All use _BASE_LATIN for structural fields; only translated strings below.

"es": {
    "metadata_fields": ["Recuento de palabras", "Tiempo de lectura", "Datos hasta", "Generado", "Modo", "Versión Skill"],
    "metadata_label": "**Metadatos**:",
    "references_label": "**Referencias**:",
    "refs_prefix": "## Referencias",
    "refs_count_format": "Total {count} fuentes",
    "toc_heading": "## Índice",
    "disclaimer_title": "## Descargo de responsabilidad",
    "disclaimer_text": "Este informe se elabora a partir de datos públicos y no constituye asesoramiento de inversión. Algunos datos dudosos están señalados.",
    "confidence_heading": "## Evaluación de Confianza",
    "verdict_labels": {"reliable": "Fiable", "moderate": "Moderado", "caution": "Precaución"},
    "report_generated": "*Informe generado: {time}*",
    "check": {
        "metadata_pattern": r'> \*\*Metadatos\*\*:',
        "references_pattern": r'> \*\*Referencias\*\*',
        "tail_refs": "## Referencias",
        "tail_disclaimer": "## Descargo de responsabilidad",
        "tail_confidence": "## Evaluación de Confianza",
    }
},

"fr": {
    "metadata_fields": ["Nombre de mots", "Temps de lecture", "Données jusqu'au", "Généré le", "Mode", "Version Skill"],
    "metadata_label": "**Métadonnées**:",
    "references_label": "**Références**:",
    "refs_prefix": "## Références",
    "refs_count_format": "Total {count} sources",
    "toc_heading": "## Table des matières",
    "disclaimer_title": "## Avertissement",
    "disclaimer_text": "Ce rapport est basé sur des données publiques et ne constitue pas un conseil en investissement. Certaines données douteuses sont signalées.",
    "confidence_heading": "## Évaluation de Confiance",
    "verdict_labels": {"reliable": "Fiable", "moderate": "Modéré", "caution": "Prudence"},
    "report_generated": "*Rapport généré : {time}*",
    "check": {
        "metadata_pattern": r'> \*\*Métadonnées\*\*:',
        "references_pattern": r'> \*\*Références\*\*',
        "tail_refs": "## Références",
        "tail_disclaimer": "## Avertissement",
        "tail_confidence": "## Évaluation de Confiance",
    }
},

"de": {
    "metadata_fields": ["Wortanzahl", "Lesezeit", "Daten bis", "Erstellt", "Modus", "Skill-Version"],
    "metadata_label": "**Metadaten**:",
    "references_label": "**Quellen**:",
    "refs_prefix": "## Quellen",
    "refs_count_format": lambda count: f"Insgesamt {count} Quelle" if count == 1 else f"Insgesamt {count} Quellen",
    "toc_heading": "## Inhaltsverzeichnis",
    "disclaimer_title": "## Haftungsausschluss",
    "disclaimer_text": "Dieser Bericht basiert auf öffentlich zugänglichen Daten und stellt keine Anlageberatung dar. Zweifelhafte Daten sind gekennzeichnet.",
    "confidence_heading": "## Vertrauensbewertung",
    "verdict_labels": {"reliable": "Zuverlässig", "moderate": "Mäßig", "caution": "Vorsicht"},
    "report_generated": "*Bericht erstellt: {time}*",
    "check": {
        "metadata_pattern": r'> \*\*Metadaten\*\*:',
        "references_pattern": r'> \*\*Quellen\*\*',
        "tail_refs": "## Quellen",
        "tail_disclaimer": "## Haftungsausschluss",
        "tail_confidence": "## Vertrauensbewertung",
    }
},

"pt": {
    "metadata_fields": ["Contagem de palavras", "Tempo de leitura", "Dados até", "Gerado em", "Modo", "Versão Skill"],
    "metadata_label": "**Metadados**:",
    "references_label": "**Referências**:",
    "refs_prefix": "## Referências",
    "refs_count_format": "Total de {count} fontes",
    "toc_heading": "## Índice",
    "disclaimer_title": "## Isenção de responsabilidade",
    "disclaimer_text": "Este relatório é baseado em dados públicos e não constitui aconselhamento de investimento. Dados duvidosos estão sinalizados.",
    "confidence_heading": "## Avaliação de Confiança",
    "verdict_labels": {"reliable": "Confiável", "moderate": "Moderado", "caution": "Cautela"},
    "report_generated": "*Relatório gerado: {time}*",
    "check": {
        "metadata_pattern": r'> \*\*Metadados\*\*:',
        "references_pattern": r'> \*\*Referências\*\*',
        "tail_refs": "## Referências",
        "tail_disclaimer": "## Isenção de responsabilidade",
        "tail_confidence": "## Avaliação de Confiança",
    }
},

"it": {
    "metadata_fields": ["Conteggio parole", "Tempo di lettura", "Dati fino al", "Generato", "Modalità", "Versione Skill"],
    "metadata_label": "**Metadati**:",
    "references_label": "**Fonti**:",
    "refs_prefix": "## Fonti",
    "refs_count_format": "Totale {count} fonti",
    "toc_heading": "## Indice",
    "disclaimer_title": "## Dichiarazione di non responsabilità",
    "disclaimer_text": "Il presente rapporto si basa su dati pubblici e non costituisce consulenza in materia di investimenti. I dati dubbi sono contrassegnati.",
    "confidence_heading": "## Valutazione di Affidabilità",
    "verdict_labels": {"reliable": "Affidabile", "moderate": "Moderato", "caution": "Attenzione"},
    "report_generated": "*Rapporto generato: {time}*",
    "check": {
        "metadata_pattern": r'> \*\*Metadati\*\*:',
        "references_pattern": r'> \*\*Fonti\*\*',
        "tail_refs": "## Fonti",
        "tail_disclaimer": "## Dichiarazione di non responsabilità",
        "tail_confidence": "## Valutazione di Affidabilità",
    }
},

"nl": {
    "metadata_fields": ["Woordenaantal", "Leestijd", "Gegevens tot", "Gegenereerd", "Modus", "Skill-versie"],
    "metadata_label": "**Metadata**:",
    "references_label": "**Bronnen**:",
    "refs_prefix": "## Bronnen",
    "refs_count_format": "Totaal {count} bronnen",
    "toc_heading": "## Inhoudsopgave",
    "disclaimer_title": "## Vrijwaring",
    "disclaimer_text": "Dit rapport is gebaseerd op openbare gegevens en vormt geen beleggingsadvies. Twijfelachtige gegevens zijn gemarkeerd.",
    "confidence_heading": "## Betrouwbaarheidsbeoordeling",
    "verdict_labels": {"reliable": "Betrouwbaar", "moderate": "Matig", "caution": "Voorzichtig"},
    "report_generated": "*Rapport gegenereerd: {time}*",
    "check": {
        "metadata_pattern": r'> \*\*Metadata\*\*:',
        "references_pattern": r'> \*\*Bronnen\*\*',
        "tail_refs": "## Bronnen",
        "tail_disclaimer": "## Vrijwaring",
        "tail_confidence": "## Betrouwbaarheidsbeoordeling",
    }
},

"sv": {
    "metadata_fields": ["Ordantal", "Lästid", "Data till", "Skapad", "Läge", "Skill-version"],
    "metadata_label": "**Metadata**:",
    "references_label": "**Källor**:",
    "refs_prefix": "## Källor",
    "refs_count_format": "Totalt {count} källor",
    "toc_heading": "## Innehållsförteckning",
    "disclaimer_title": "## Ansvarsfriskrivning",
    "disclaimer_text": "Denna rapport är baserad på offentligt tillgängliga data och utgör inte investeringsrådgivning. Tveksamma data är markerade.",
    "confidence_heading": "## Förtroendebedömning",
    "verdict_labels": {"reliable": "Tillförlitlig", "moderate": "Måttlig", "caution": "Försiktighet"},
    "report_generated": "*Rapport genererad: {time}*",
    "check": {
        "metadata_pattern": r'> \*\*Metadata\*\*:',
        "references_pattern": r'> \*\*Källor\*\*',
        "tail_refs": "## Källor",
        "tail_disclaimer": "## Ansvarsfriskrivning",
        "tail_confidence": "## Förtroendebedömning",
    }
},

"ru": {
    "metadata_fields": ["Количество слов", "Время чтения", "Данные до", "Создано", "Режим", "Версия Skill"],
    "metadata_label": "**Метаданные**:",
    "references_label": "**Источники**:",
    "refs_prefix": "## Источники",
    "refs_count_format": "Всего {count} источников",
    "toc_heading": "## Содержание",
    "disclaimer_title": "## Отказ от ответственности",
    "disclaimer_text": "Данный отчет основан на общедоступных данных и не является инвестиционной рекомендацией. Сомнительные данные отмечены.",
    "confidence_heading": "## Оценка достоверности",
    "verdict_labels": {"reliable": "Надёжно", "moderate": "Умеренно", "caution": "Осторожно"},
    "report_generated": "*Отчет создан: {time}*",
    "check": {
        "metadata_pattern": r'> \*\*Метаданные\*\*:',
        "references_pattern": r'> \*\*Источники\*\*',
        "tail_refs": "## Источники",
        "tail_disclaimer": "## Отказ от ответственности",
        "tail_confidence": "## Оценка достоверности",
    }
},

# ── RTL / non-Latin script languages ──

"ar": {
    "metadata_fields": ["عدد الكلمات", "وقت القراءة", "البيانات حتى", "تاريخ الإنشاء", "الوضع", "إصدار المهارة"],
    "metadata_label": "**البيانات الوصفية**:",
    "references_label": "**المصادر**:",
    "refs_prefix": "## المصادر",
    "refs_count_format": "إجمالي {count} مصدرًا",
    "toc_heading": "## المحتويات",
    "disclaimer_title": "## إخلاء المسؤولية",
    "disclaimer_text": "يعتمد هذا التقرير على بيانات متاحة للعموم ولا يشكل نصيحة استثمارية. تم وضع علامات على البيانات المشكوك فيها.",
    "confidence_heading": "## تقييم الثقة",
    "verdict_labels": {"reliable": "موثوق", "moderate": "معتدل", "caution": "حذر"},
    "report_generated": "*تاريخ إنشاء التقرير: {time}*",
    "check": {
        "metadata_pattern": r'> \*\*البيانات الوصفية\*\*:',
        "references_pattern": r'> \*\*المصادر\*\*',
        "tail_refs": "## المصادر",
        "tail_disclaimer": "## إخلاء المسؤولية",
        "tail_confidence": "## تقييم الثقة",
    }
},

"hi": {
    "metadata_fields": ["शब्द गणना", "पढ़ने का समय", "डेटा तक", "निर्माण समय", "मोड", "कौशल संस्करण"],
    "metadata_label": "**मेटाडेटा**:",
    "references_label": "**स्रोत**:",
    "refs_prefix": "## स्रोत",
    "refs_count_format": "कुल {count} स्रोत",
    "toc_heading": "## विषय सूची",
    "disclaimer_title": "## अस्वीकरण",
    "disclaimer_text": "यह रिपोर्ट सार्वजनिक डेटा पर आधारित है और निवेश सलाह का गठन नहीं करती है। संदिग्ध डेटा को चिह्नित किया गया है।",
    "confidence_heading": "## विश्वसनीयता मूल्यांकन",
    "verdict_labels": {"reliable": "विश्वसनीय", "moderate": "मध्यम", "caution": "सावधान"},
    "report_generated": "*रिपोर्ट निर्माण समय: {time}*",
    "check": {
        "metadata_pattern": r'> \*\*मेटाडेटा\*\*:',
        "references_pattern": r'> \*\*स्रोत\*\*',
        "tail_refs": "## स्रोत",
        "tail_disclaimer": "## अस्वीकरण",
        "tail_confidence": "## विश्वसनीयता मूल्यांकन",
    }
},

"vi": {
    "metadata_fields": ["Số từ", "Thời gian đọc", "Dữ liệu đến", "Tạo lúc", "Chế độ", "Phiên bản Skill"],
    "metadata_label": "**Siêu dữ liệu**:",
    "references_label": "**Nguồn tham khảo**:",
    "refs_prefix": "## Nguồn tham khảo",
    "refs_count_format": "Tổng số {count} nguồn",
    "toc_heading": "## Mục lục",
    "disclaimer_title": "## Tuyên bố miễn trách",
    "disclaimer_text": "Báo cáo này được tổng hợp từ dữ liệu công khai và không cấu thành lời khuyên đầu tư. Dữ liệu nghi ngờ đã được đánh dấu.",
    "confidence_heading": "## Đánh giá độ tin cậy",
    "verdict_labels": {"reliable": "Đáng tin cậy", "moderate": "Trung bình", "caution": "Thận trọng"},
    "report_generated": "*Báo cáo tạo lúc: {time}*",
    "check": {
        "metadata_pattern": r'> \*\*Siêu dữ liệu\*\*:',
        "references_pattern": r'> \*\*Nguồn tham khảo\*\*',
        "tail_refs": "## Nguồn tham khảo",
        "tail_disclaimer": "## Tuyên bố miễn trách",
        "tail_confidence": "## Đánh giá độ tin cậy",
    }
},

"id": {
    "metadata_fields": ["Jumlah kata", "Waktu baca", "Data hingga", "Dibuat", "Mode", "Versi Skill"],
    "metadata_label": "**Metadata**:",
    "references_label": "**Referensi**:",
    "refs_prefix": "## Referensi",
    "refs_count_format": "Total {count} sumber",
    "toc_heading": "## Daftar Isi",
    "disclaimer_title": "## Penyangkalan",
    "disclaimer_text": "Laporan ini disusun berdasarkan data publik dan tidak merupakan saran investasi. Data yang meragukan telah ditandai.",
    "confidence_heading": "## Penilaian Kepercayaan",
    "verdict_labels": {"reliable": "Terpercaya", "moderate": "Sedang", "caution": "Hati-hati"},
    "report_generated": "*Laporan dibuat: {time}*",
    "check": {
        "metadata_pattern": r'> \*\*Metadata\*\*:',
        "references_pattern": r'> \*\*Referensi\*\*',
        "tail_refs": "## Referensi",
        "tail_disclaimer": "## Penyangkalan",
        "tail_confidence": "## Penilaian Kepercayaan",
    }
},

"th": {
    "metadata_fields": ["จำนวนคำ", "เวลาอ่าน", "ข้อมูลถึง", "สร้างเมื่อ", "โหมด", "เวอร์ชัน Skill"],
    "metadata_label": "**ข้อมูลเมตา**:",
    "references_label": "**แหล่งอ้างอิง**:",
    "refs_prefix": "## แหล่งอ้างอิง",
    "refs_count_format": "รวม {count} แหล่งที่มา",
    "toc_heading": "## สารบัญ",
    "disclaimer_title": "## ข้อจำกัดความรับผิดชอบ",
    "disclaimer_text": "รายงานนี้รวบรวมจากข้อมูลสาธารณะและไม่ถือเป็นคำแนะนำด้านการลงทุน ข้อมูลที่น่าสงสัยถูกทำเครื่องหมายไว้",
    "confidence_heading": "## การประเมินความน่าเชื่อถือ",
    "verdict_labels": {"reliable": "เชื่อถือได้", "moderate": "ปานกลาง", "caution": "ระวัง"},
    "report_generated": "*รายงานสร้างเมื่อ: {time}*",
    "check": {
        "metadata_pattern": r'> \*\*ข้อมูลเมตา\*\*:',
        "references_pattern": r'> \*\*แหล่งอ้างอิง\*\*',
        "tail_refs": "## แหล่งอ้างอิง",
        "tail_disclaimer": "## ข้อจำกัดความรับผิดชอบ",
        "tail_confidence": "## การประเมินความน่าเชื่อถือ",
    }
},

"tr": {
    "metadata_fields": ["Kelime sayısı", "Okuma süresi", "Veri tarihine kadar", "Oluşturma zamanı", "Mod", "Skill Sürümü"],
    "metadata_label": "**Meta veri**:",
    "references_label": "**Kaynaklar**:",
    "refs_prefix": "## Kaynaklar",
    "refs_count_format": "Toplam {count} kaynak",
    "toc_heading": "## İçindekiler",
    "disclaimer_title": "## Sorumluluk reddi",
    "disclaimer_text": "Bu rapor kamuya açık verilere dayanmaktadır ve yatırım tavsiyesi niteliği taşımaz. Şüpheli veriler işaretlenmiştir.",
    "confidence_heading": "## Güven Değerlendirmesi",
    "verdict_labels": {"reliable": "Güvenilir", "moderate": "Orta", "caution": "Dikkat"},
    "report_generated": "*Rapor oluşturma zamanı: {time}*",
    "check": {
        "metadata_pattern": r'> \*\*Meta veri\*\*:',
        "references_pattern": r'> \*\*Kaynaklar\*\*',
        "tail_refs": "## Kaynaklar",
        "tail_disclaimer": "## Sorumluluk reddi",
        "tail_confidence": "## Güven Değerlendirmesi",
    }
},

"pl": {
    "metadata_fields": ["Liczba słów", "Czas czytania", "Dane do", "Wygenerowano", "Tryb", "Wersja Skill"],
    "metadata_label": "**Metadane**:",
    "references_label": "**Źródła**:",
    "refs_prefix": "## Źródła",
    "refs_count_format": "Łącznie {count} źródeł",
    "toc_heading": "## Spis treści",
    "disclaimer_title": "## Zrzeczenie się odpowiedzialności",
    "disclaimer_text": "Raport został opracowany na podstawie danych publicznych i nie stanowi porady inwestycyjnej. Wątpliwe dane zostały oznaczone.",
    "confidence_heading": "## Ocena Wiarygodności",
    "verdict_labels": {"reliable": "Godny zaufania", "moderate": "Umiarkowany", "caution": "Ostrożność"},
    "report_generated": "*Raport wygenerowano: {time}*",
    "check": {
        "metadata_pattern": r'> \*\*Metadane\*\*:',
        "references_pattern": r'> \*\*Źródła\*\*',
        "tail_refs": "## Źródła",
        "tail_disclaimer": "## Zrzeczenie się odpowiedzialności",
        "tail_confidence": "## Ocena Wiarygodności",
    }
},

}  # end _LANG


# Confidence section labels are kept separate so the aggregation code remains
# language-neutral and every supported report language receives native labels.
_CONFIDENCE_LABELS = {
    "zh": {
        "source_type": "来源类型（粗分）", "authoritative": "学术/机构", "industry": "行业", "media": "媒体",
        "data_type": "数据类型", "actual": "已公布", "estimate": "估算", "forecast": "预测",
        "distribution": "置信度分布", "high": "高置信", "medium": "中等", "low": "低置信",
        "coverage": "覆盖度", "adequate": "充足", "insufficient": "不足",
        "limitations": "数据限制", "limited": "有（部分子问题数据覆盖不足，结论需谨慎参考）", "none": "无",
        "discrepancies": "跨源矛盾", "discrepancy_note": "处跨源数据差异，已在正文对应章节并排呈现",
        "rating": "综合评级", "no_data": "无数据",
        "inference_note": "注：部分事实未显式标注 conf/data_type，以上置信度与数据类型由来源与上下文自动推断。",
    },
    "en": {
        "source_type": "Source Type", "authoritative": "Academic/Institutional", "industry": "Industry", "media": "Media",
        "data_type": "Data Type", "actual": "Actual", "estimate": "Estimate", "forecast": "Forecast",
        "distribution": "Confidence Distribution", "high": "High", "medium": "Medium", "low": "Low",
        "coverage": "Coverage", "adequate": "Adequate", "insufficient": "Insufficient",
        "limitations": "Data Limitations", "limited": "Yes (some sub-questions have insufficient coverage; interpret conclusions with caution)", "none": "None",
        "discrepancies": "Cross-source Discrepancies", "discrepancy_note": "cross-source discrepancies are presented side by side in the relevant chapters",
        "rating": "Rating", "no_data": "No data",
        "inference_note": "Note: some facts lack explicit conf/data_type fields; confidence and data types are inferred from sources and context.",
    },
    "ja": {
        "source_type": "情報源区分（概算）", "authoritative": "学術・公的機関", "industry": "業界", "media": "メディア",
        "data_type": "データ種別", "actual": "公表済み", "estimate": "推計", "forecast": "予測",
        "distribution": "信頼度分布", "high": "高", "medium": "中", "low": "低",
        "coverage": "カバレッジ", "adequate": "十分", "insufficient": "不十分",
        "limitations": "データ上の制約", "limited": "あり（一部の小問は情報が限定的なため、結論は慎重に参照してください）", "none": "なし",
        "discrepancies": "情報源間の相違", "discrepancy_note": "件の情報源間の相違を該当章で併記",
        "rating": "総合評価", "no_data": "データなし",
        "inference_note": "注：一部の事実には conf/data_type の明示がないため、情報源と文脈から信頼度とデータ種別を推定しています。",
    },
    "ko": {
        "source_type": "출처 유형(개략)", "authoritative": "학술·기관", "industry": "산업", "media": "미디어",
        "data_type": "데이터 유형", "actual": "공개 수치", "estimate": "추정", "forecast": "전망",
        "distribution": "신뢰도 분포", "high": "높음", "medium": "보통", "low": "낮음",
        "coverage": "포괄 범위", "adequate": "충분", "insufficient": "부족",
        "limitations": "데이터 제약", "limited": "있음(일부 세부 질문의 자료가 부족하므로 결론을 신중히 참고해야 함)", "none": "없음",
        "discrepancies": "출처 간 차이", "discrepancy_note": "건의 출처 간 차이를 관련 장에 나란히 제시",
        "rating": "종합 평가", "no_data": "데이터 없음",
        "inference_note": "참고: 일부 사실에 conf/data_type이 명시되지 않아 출처와 문맥을 바탕으로 신뢰도와 데이터 유형을 추론했습니다.",
    },
    "ru": {
        "source_type": "Тип источника (оценочно)", "authoritative": "Научные/официальные", "industry": "Отраслевые", "media": "СМИ",
        "data_type": "Тип данных", "actual": "Опубликованные", "estimate": "Оценочные", "forecast": "Прогнозные",
        "distribution": "Распределение достоверности", "high": "Высокая", "medium": "Средняя", "low": "Низкая",
        "coverage": "Охват", "adequate": "Достаточный", "insufficient": "Недостаточный",
        "limitations": "Ограничения данных", "limited": "Есть (по части вопросов охват недостаточен; выводы следует трактовать осторожно)", "none": "Нет",
        "discrepancies": "Расхождения между источниками", "discrepancy_note": "расхождений между источниками сопоставлены в соответствующих главах",
        "rating": "Итоговая оценка", "no_data": "Нет данных",
        "inference_note": "Примечание: для части фактов поля conf/data_type не указаны; достоверность и тип данных определены по источнику и контексту.",
    },
    "ar": {
        "source_type": "نوع المصدر (تقريبي)", "authoritative": "أكاديمي/مؤسسي", "industry": "قطاعي", "media": "إعلامي",
        "data_type": "نوع البيانات", "actual": "منشورة", "estimate": "تقديرية", "forecast": "تنبؤية",
        "distribution": "توزيع الثقة", "high": "مرتفعة", "medium": "متوسطة", "low": "منخفضة",
        "coverage": "التغطية", "adequate": "كافية", "insufficient": "غير كافية",
        "limitations": "قيود البيانات", "limited": "موجودة (تغطية بعض الأسئلة الفرعية محدودة؛ ينبغي تفسير النتائج بحذر)", "none": "لا توجد",
        "discrepancies": "اختلافات بين المصادر", "discrepancy_note": "اختلافات بين المصادر معروضة جنبًا إلى جنب في الفصول المعنية",
        "rating": "التقييم الإجمالي", "no_data": "لا توجد بيانات",
        "inference_note": "ملاحظة: بعض الحقائق لا تتضمن حقلي conf/data_type صراحةً؛ تم استنتاج الثقة ونوع البيانات من المصدر والسياق.",
    },
    "hi": {
        "source_type": "स्रोत प्रकार (अनुमानित)", "authoritative": "शैक्षणिक/संस्थागत", "industry": "उद्योग", "media": "मीडिया",
        "data_type": "डेटा प्रकार", "actual": "प्रकाशित", "estimate": "अनुमान", "forecast": "पूर्वानुमान",
        "distribution": "विश्वसनीयता वितरण", "high": "उच्च", "medium": "मध्यम", "low": "निम्न",
        "coverage": "कवरेज", "adequate": "पर्याप्त", "insufficient": "अपर्याप्त",
        "limitations": "डेटा सीमाएँ", "limited": "हैं (कुछ उप-प्रश्नों का कवरेज अपर्याप्त है; निष्कर्षों को सावधानी से पढ़ें)", "none": "कोई नहीं",
        "discrepancies": "स्रोतों के बीच अंतर", "discrepancy_note": "स्रोत-अंतर संबंधित अध्यायों में साथ-साथ प्रस्तुत किए गए हैं",
        "rating": "समग्र रेटिंग", "no_data": "डेटा उपलब्ध नहीं",
        "inference_note": "नोट: कुछ तथ्यों में conf/data_type स्पष्ट नहीं हैं; विश्वसनीयता और डेटा प्रकार स्रोत व संदर्भ से अनुमानित हैं।",
    },
    "vi": {
        "source_type": "Loại nguồn (ước phân)", "authoritative": "Học thuật/tổ chức", "industry": "Ngành", "media": "Truyền thông",
        "data_type": "Loại dữ liệu", "actual": "Đã công bố", "estimate": "Ước tính", "forecast": "Dự báo",
        "distribution": "Phân bố độ tin cậy", "high": "Cao", "medium": "Trung bình", "low": "Thấp",
        "coverage": "Mức độ bao phủ", "adequate": "Đủ", "insufficient": "Chưa đủ",
        "limitations": "Hạn chế dữ liệu", "limited": "Có (một số câu hỏi phụ chưa được bao phủ đầy đủ; cần diễn giải kết luận thận trọng)", "none": "Không",
        "discrepancies": "Chênh lệch giữa các nguồn", "discrepancy_note": "chênh lệch giữa các nguồn được trình bày song song trong các chương liên quan",
        "rating": "Đánh giá tổng hợp", "no_data": "Không có dữ liệu",
        "inference_note": "Lưu ý: một số dữ kiện không ghi rõ conf/data_type; độ tin cậy và loại dữ liệu được suy ra từ nguồn và ngữ cảnh.",
    },
    "th": {
        "source_type": "ประเภทแหล่งข้อมูล (โดยประมาณ)", "authoritative": "วิชาการ/สถาบัน", "industry": "อุตสาหกรรม", "media": "สื่อ",
        "data_type": "ประเภทข้อมูล", "actual": "เผยแพร่แล้ว", "estimate": "ค่าประมาณ", "forecast": "คาดการณ์",
        "distribution": "การกระจายความเชื่อมั่น", "high": "สูง", "medium": "ปานกลาง", "low": "ต่ำ",
        "coverage": "ความครอบคลุม", "adequate": "เพียงพอ", "insufficient": "ไม่เพียงพอ",
        "limitations": "ข้อจำกัดของข้อมูล", "limited": "มี (คำถามย่อยบางส่วนมีข้อมูลไม่เพียงพอ ควรตีความข้อสรุปอย่างระมัดระวัง)", "none": "ไม่มี",
        "discrepancies": "ความแตกต่างระหว่างแหล่งข้อมูล", "discrepancy_note": "จุดแตกต่างระหว่างแหล่งข้อมูลแสดงเทียบกันในบทที่เกี่ยวข้อง",
        "rating": "การประเมินโดยรวม", "no_data": "ไม่มีข้อมูล",
        "inference_note": "หมายเหตุ: ข้อเท็จจริงบางรายการไม่ได้ระบุ conf/data_type จึงอนุมานความเชื่อมั่นและประเภทข้อมูลจากแหล่งที่มาและบริบท",
    },
    "tr": {
        "source_type": "Kaynak türü (yaklaşık)", "authoritative": "Akademik/kurumsal", "industry": "Sektör", "media": "Medya",
        "data_type": "Veri türü", "actual": "Yayımlanmış", "estimate": "Tahmin", "forecast": "Öngörü",
        "distribution": "Güven dağılımı", "high": "Yüksek", "medium": "Orta", "low": "Düşük",
        "coverage": "Kapsam", "adequate": "Yeterli", "insufficient": "Yetersiz",
        "limitations": "Veri sınırlamaları", "limited": "Var (bazı alt soruların kapsamı yetersiz; sonuçlar dikkatle yorumlanmalıdır)", "none": "Yok",
        "discrepancies": "Kaynaklar arası farklılıklar", "discrepancy_note": "kaynaklar arası farklılık ilgili bölümlerde yan yana sunuldu",
        "rating": "Genel değerlendirme", "no_data": "Veri yok",
        "inference_note": "Not: bazı olgularda conf/data_type açıkça belirtilmemiştir; güven ve veri türü kaynak ile bağlamdan çıkarılmıştır.",
    },
    "es": {
        "source_type": "Tipo de fuente (aprox.)", "authoritative": "Académica/institucional", "industry": "Sectorial", "media": "Medios",
        "data_type": "Tipo de datos", "actual": "Publicados", "estimate": "Estimación", "forecast": "Previsión",
        "distribution": "Distribución de confianza", "high": "Alta", "medium": "Media", "low": "Baja",
        "coverage": "Cobertura", "adequate": "Adecuada", "insufficient": "Insuficiente",
        "limitations": "Limitaciones de los datos", "limited": "Sí (algunas subpreguntas tienen cobertura insuficiente; las conclusiones deben interpretarse con cautela)", "none": "Ninguna",
        "discrepancies": "Discrepancias entre fuentes", "discrepancy_note": "discrepancias entre fuentes se presentan en paralelo en los capítulos pertinentes",
        "rating": "Calificación general", "no_data": "Sin datos",
        "inference_note": "Nota: algunos hechos no indican conf/data_type de forma explícita; la confianza y el tipo de datos se infieren de la fuente y el contexto.",
    },
    "fr": {
        "source_type": "Type de source (approx.)", "authoritative": "Académique/institutionnelle", "industry": "Sectorielle", "media": "Médias",
        "data_type": "Type de données", "actual": "Publiées", "estimate": "Estimation", "forecast": "Prévision",
        "distribution": "Répartition de la confiance", "high": "Élevée", "medium": "Moyenne", "low": "Faible",
        "coverage": "Couverture", "adequate": "Suffisante", "insufficient": "Insuffisante",
        "limitations": "Limites des données", "limited": "Oui (certaines sous-questions sont insuffisamment couvertes ; les conclusions doivent être interprétées avec prudence)", "none": "Aucune",
        "discrepancies": "Écarts entre sources", "discrepancy_note": "écarts entre sources sont présentés côte à côte dans les chapitres concernés",
        "rating": "Évaluation globale", "no_data": "Aucune donnée",
        "inference_note": "Note : certains faits ne précisent pas conf/data_type ; la confiance et le type de données sont déduits de la source et du contexte.",
    },
    "de": {
        "source_type": "Quellentyp (grob)", "authoritative": "Wissenschaftlich/institutionell", "industry": "Branche", "media": "Medien",
        "data_type": "Datentyp", "actual": "Veröffentlicht", "estimate": "Schätzung", "forecast": "Prognose",
        "distribution": "Verteilung der Verlässlichkeit", "high": "Hoch", "medium": "Mittel", "low": "Niedrig",
        "coverage": "Abdeckung", "adequate": "Ausreichend", "insufficient": "Unzureichend",
        "limitations": "Dateneinschränkungen", "limited": "Vorhanden (einige Teilfragen sind unzureichend abgedeckt; Schlussfolgerungen sind vorsichtig zu interpretieren)", "none": "Keine",
        "discrepancies": "Abweichungen zwischen Quellen", "discrepancy_note": "Abweichungen zwischen Quellen werden in den betreffenden Kapiteln gegenübergestellt",
        "rating": "Gesamtbewertung", "no_data": "Keine Daten",
        "inference_note": "Hinweis: Bei einigen Fakten fehlen explizite conf/data_type-Angaben; Verlässlichkeit und Datentyp wurden aus Quelle und Kontext abgeleitet.",
    },
    "pt": {
        "source_type": "Tipo de fonte (aprox.)", "authoritative": "Acadêmica/institucional", "industry": "Setorial", "media": "Mídia",
        "data_type": "Tipo de dados", "actual": "Publicados", "estimate": "Estimativa", "forecast": "Previsão",
        "distribution": "Distribuição de confiança", "high": "Alta", "medium": "Média", "low": "Baixa",
        "coverage": "Cobertura", "adequate": "Adequada", "insufficient": "Insuficiente",
        "limitations": "Limitações dos dados", "limited": "Sim (algumas subquestões têm cobertura insuficiente; as conclusões devem ser interpretadas com cautela)", "none": "Nenhuma",
        "discrepancies": "Divergências entre fontes", "discrepancy_note": "divergências entre fontes são apresentadas lado a lado nos capítulos pertinentes",
        "rating": "Avaliação geral", "no_data": "Sem dados",
        "inference_note": "Nota: alguns fatos não informam conf/data_type explicitamente; a confiança e o tipo de dados são inferidos da fonte e do contexto.",
    },
    "it": {
        "source_type": "Tipo di fonte (stima)", "authoritative": "Accademica/istituzionale", "industry": "Settore", "media": "Media",
        "data_type": "Tipo di dati", "actual": "Pubblicati", "estimate": "Stima", "forecast": "Previsione",
        "distribution": "Distribuzione dell'affidabilità", "high": "Alta", "medium": "Media", "low": "Bassa",
        "coverage": "Copertura", "adequate": "Adeguata", "insufficient": "Insufficiente",
        "limitations": "Limiti dei dati", "limited": "Presenti (alcune sotto-domande hanno copertura insufficiente; le conclusioni vanno interpretate con cautela)", "none": "Nessuno",
        "discrepancies": "Divergenze tra fonti", "discrepancy_note": "divergenze tra fonti sono presentate a confronto nei capitoli pertinenti",
        "rating": "Valutazione complessiva", "no_data": "Nessun dato",
        "inference_note": "Nota: alcuni fatti non specificano conf/data_type; affidabilità e tipo di dati sono dedotti dalla fonte e dal contesto.",
    },
    "nl": {
        "source_type": "Brontype (globaal)", "authoritative": "Academisch/institutioneel", "industry": "Sector", "media": "Media",
        "data_type": "Datatype", "actual": "Gepubliceerd", "estimate": "Schatting", "forecast": "Prognose",
        "distribution": "Betrouwbaarheidsverdeling", "high": "Hoog", "medium": "Gemiddeld", "low": "Laag",
        "coverage": "Dekking", "adequate": "Voldoende", "insufficient": "Onvoldoende",
        "limitations": "Databeperkingen", "limited": "Aanwezig (enkele deelvragen zijn onvoldoende gedekt; interpreteer de conclusies voorzichtig)", "none": "Geen",
        "discrepancies": "Verschillen tussen bronnen", "discrepancy_note": "verschillen tussen bronnen worden in de relevante hoofdstukken naast elkaar getoond",
        "rating": "Eindbeoordeling", "no_data": "Geen gegevens",
        "inference_note": "Opmerking: bij sommige feiten ontbreken expliciete conf/data_type-velden; betrouwbaarheid en datatype zijn afgeleid uit bron en context.",
    },
    "sv": {
        "source_type": "Källtyp (översiktlig)", "authoritative": "Akademisk/institutionell", "industry": "Bransch", "media": "Medier",
        "data_type": "Datatyp", "actual": "Publicerade", "estimate": "Uppskattning", "forecast": "Prognos",
        "distribution": "Tillförlitlighetsfördelning", "high": "Hög", "medium": "Medel", "low": "Låg",
        "coverage": "Täckning", "adequate": "Tillräcklig", "insufficient": "Otillräcklig",
        "limitations": "Databegränsningar", "limited": "Finns (vissa delfrågor har otillräcklig täckning; slutsatserna bör tolkas försiktigt)", "none": "Inga",
        "discrepancies": "Skillnader mellan källor", "discrepancy_note": "skillnader mellan källor redovisas sida vid sida i berörda kapitel",
        "rating": "Samlad bedömning", "no_data": "Inga data",
        "inference_note": "Obs: vissa fakta saknar uttryckliga conf/data_type-fält; tillförlitlighet och datatyp har härletts från källa och sammanhang.",
    },
    "pl": {
        "source_type": "Typ źródła (ogólnie)", "authoritative": "Naukowe/instytucjonalne", "industry": "Branżowe", "media": "Media",
        "data_type": "Typ danych", "actual": "Opublikowane", "estimate": "Szacunek", "forecast": "Prognoza",
        "distribution": "Rozkład wiarygodności", "high": "Wysoka", "medium": "Średnia", "low": "Niska",
        "coverage": "Pokrycie", "adequate": "Wystarczające", "insufficient": "Niewystarczające",
        "limitations": "Ograniczenia danych", "limited": "Występują (część pytań ma niewystarczające pokrycie; wnioski należy interpretować ostrożnie)", "none": "Brak",
        "discrepancies": "Rozbieżności między źródłami", "discrepancy_note": "rozbieżności między źródłami zestawiono w odpowiednich rozdziałach",
        "rating": "Ocena ogólna", "no_data": "Brak danych",
        "inference_note": "Uwaga: część faktów nie ma jawnych pól conf/data_type; wiarygodność i typ danych wywnioskowano ze źródła i kontekstu.",
    },
    "id": {
        "source_type": "Jenis sumber (perkiraan)", "authoritative": "Akademik/institusional", "industry": "Industri", "media": "Media",
        "data_type": "Jenis data", "actual": "Dipublikasikan", "estimate": "Estimasi", "forecast": "Prakiraan",
        "distribution": "Distribusi kepercayaan", "high": "Tinggi", "medium": "Sedang", "low": "Rendah",
        "coverage": "Cakupan", "adequate": "Memadai", "insufficient": "Tidak memadai",
        "limitations": "Keterbatasan data", "limited": "Ada (beberapa subpertanyaan belum tercakup memadai; simpulan perlu ditafsirkan dengan hati-hati)", "none": "Tidak ada",
        "discrepancies": "Perbedaan antarsumber", "discrepancy_note": "perbedaan antarsumber disajikan berdampingan pada bab terkait",
        "rating": "Penilaian keseluruhan", "no_data": "Tidak ada data",
        "inference_note": "Catatan: sebagian fakta tidak mencantumkan conf/data_type secara eksplisit; tingkat kepercayaan dan jenis data disimpulkan dari sumber dan konteks.",
    },
}


# ── Build LANG_CONFIG by merging base template + per-language overrides ──

LANG_CONFIG = {}
for code, overrides in _LANG.items():
    base = dict(_BASE_ZH if code == "zh" else _BASE_LATIN)
    # Merge check dict
    if 'check' in overrides:
        merged_check = dict(base.get('check', {}))
        merged_check.update(overrides.pop('check'))
        overrides['check'] = merged_check
    base.update(overrides)
    base["confidence_labels"] = _CONFIDENCE_LABELS[code]
    LANG_CONFIG[code] = base


def get_lang_config(lang: str) -> dict:
    """Get language config. Falls back to English for unsupported languages."""
    return LANG_CONFIG.get(lang, LANG_CONFIG["en"])
